[package]
name = "misc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cube = { version = "0.0.0", path = "../cube" }
cube_bld = { version = "0.1.0", path = "../cube_bld" }
