[package]
name = "sheet_dumper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
calamine = "0.22.1"
csv = "1.3.0"
num_cpus = "1.16.0"
rusqlite = "0.30.0"
