name: Deploy page

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "bld.tadeo.ca"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.74.0"
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: v0.12.1
      - run: wasm-pack build crates/bld_tadeo_ca --target web --release
      - run: mkdir out && cp -r crates/bld_tadeo_ca/{index.html,main.js,pkg} out
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "out"
      - id: deployment
        uses: actions/deploy-pages@v3
